---
title: The Technology and Social Justice Field Scan
timezone: UTC
collections:
  organizations:
    title: Organizations
    output: true
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: people
  values:
    header-photo: ''
    photo: ''
    twitter: ''
    role: ''
    organization: ''
- scope:
    path: ''
    type: posts
  values:
    header-photo: ''
email: maya@opentechinstitute.org
description: This is the website for the Technology and Social Justice Field Scan,
  a participatory action research project to understand how people and what people
  build technologies for social good.
baseurl: 
url: 
twitter_username: tech4socialjust
github_username: mayawagon
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
include:
- uploads
sass:
  sass_dir: _sass
